cache: pip
dist: xenial
language: python
sudo: required

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

allow_failure:
    - python: "3.8"

install:
    - pip install -r requirements.txt

before_script:
    - make prepare
    - make install-db

script:
    - pip freeze
    - make test-ci

after_success:
    - make upload-coverage

deploy:
    provider: script
    script: make upload-pypi
    on:
        python: 3.8
        tags: true

notifications:
    email: false
