sudo: false
language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install -r requirements.txt

jobs:
    include:
        - stage: upload_coverage
          script: make test-coverage

        - stage: integration_test
          if: branch = master
          script: make test-integration

before_script:
    - make prepare
    
script:
    - make test-unit
    
after_success:
    - make upload-coverage
