language: python
sudo: false

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install -r requirements.txt

jobs:
    include:
        - stage: prepare
          script: make prepare

        - stage: unit_test
          script: make test-unit

        - stage: upload_coverage
          script: make test-coverage

        - stage: integration_test
          if: branch = master
          script: make test-integration
